# Generated by Django 5.2.4 on 2025-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_assignment_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.JSONField(choices=[('STATE_PUBLIC', 'Public'), ('STATE_DRAFT', 'Draft'), ('STATE_ARCHIVED', 'Archived')], help_text='Select an appropriate state.'),
        ),
    ]
