# Generated by Django 5.2.4 on 2025-07-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_assignment_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.JSONField(choices=[('STATE_PUBLIC', 'Public'), ('STATE_DRAFT', 'Draft'), ('STATE_ARCHIVED', 'Archived')]),
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('type', models.JSONField(choices=[('TYPE_GENERAL', 'General'), ('TYPE_SPECIAL', 'Specialised')])),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255, null=True)),
                ('group', models.JSONField(choices=[('GROUP_GENERAL', 'General'), ('GROUP_SPECIAL', 'Specialised')])),
                ('weight', models.IntegerField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'High')], default=1)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('descriptors', models.ManyToManyField(default='GROUP_GENERAL', to='projects.descriptor')),
            ],
        ),
    ]
