# Generated by Django 5.2.4 on 2025-07-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_assignment_state_descriptor_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='criteria',
            field=models.ManyToManyField(to='projects.criterion'),
        ),
    ]
