# Generated by Django 5.2.4 on 2025-08-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0005_assignment_criteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher',
            new_name='author',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(max_length=4000, null=True)),
                ('state', models.JSONField(choices=[('STATE_DRAFT', 'Draft: working on it'), ('STATE_REVIEW', 'Review: changes needed'), ('STATE_FINISHED', 'Finished: done'), ('STATE_ARCHIVED', 'Archived: stored for me')])),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(null=True, to='core.file')),
            ],
        ),
    ]
