# Generated by Django 5.2.4 on 2025-08-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255, null=True)),
                ('path', models.FileField(null=True, upload_to='storage/')),
                ('meta', models.JSONField(null=True)),
                ('state', models.JSONField(choices=[('STATE_PUBLIC', 'Public: everyone can see'), ('STATE_DRAFT', 'Draft: working on it'), ('STATE_ARCHIVED', 'Archived: stored for me')])),
                ('version', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
