# Generated by Django 5.2.4 on 2025-07-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_text',
            new_name='text',
        ),
    ]
