# Generated by Django 5.2.4 on 2025-07-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.staff'),
            preserve_default=False,
        ),
    ]
