# Generated by Django 5.2.4 on 2025-07-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_set_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='type',
            field=models.CharField(choices=[('TYPE_YEAR', 'Year Group'), ('TYPE_TUTOR', 'Tutor Group'), ('TYPE_PERFORM', 'Performance'), ('TYPE_INTEREST', 'Interests')], max_length=100),
        ),
    ]
