# Generated by Django 5.2.4 on 2025-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_subject_lead_topic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('ROLE_TEACHER', 'Teacher')], default='ROLE_TEACHER'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lead',
        ),
        migrations.AddField(
            model_name='subject',
            name='lead',
            field=models.ManyToManyField(to='settings.staff'),
        ),
    ]
