# Generated by Django 5.2.4 on 2025-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_staff_type_remove_subject_lead_subject_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('ROLE_TEACHER', 'Teacher')], default='ROLE_TEACHER', help_text='Select an appropriate account type.'),
        ),
    ]
