# Generated by Django 5.2.4 on 2025-07-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_staff_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.JSONField(choices=[('ROLE_STUDENT', 'Student'), ('ROLE_INSTRUCTOR', 'Teaching student/Instructor'), ('ROLE_TEACHER', 'Teacher'), ('ROLE_ADMIN', 'Admin staff')], default='ROLE_STUDENT', help_text='Select an appropriate role.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='lead',
            field=models.ManyToManyField(to='settings.member'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.member'),
        ),
    ]
