# Generated by Django 5.2.4 on 2025-07-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignment_teacher'),
        ('settings', '0007_remove_staff_user_member_alter_subject_lead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
