# Generated by Django 5.2.4 on 2025-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.JSONField(choices=[('ROLE_STUDENT', 'Student'), ('ROLE_INSTRUCTOR', 'Teaching student/Instructor'), ('ROLE_TEACHER', 'Teacher'), ('ROLE_ADMIN', 'Admin staff')], default={'ROLE_STUDENT': 'Student'}, help_text='Select an appropriate role.'),
        ),
    ]
