# Generated by Django 5.2.4 on 2025-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.JSONField(choices=[('ST', 'Student'), ('IN', 'Instructor'), ('TR', 'Teacher'), ('AD', 'Admin')], help_text='Select an appropriate role.'),
        ),
    ]
