# Generated by Django 5.2.4 on 2025-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.CharField(choices=[('Public', 'Public'), (None, 'Pick the status.')], default='Public'),
        ),
    ]
