# Generated by Django 5.2.4 on 2025-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.CharField(choices=[('Public', 'Public')], default='Public'),
        ),
    ]
