# Generated by Django 5.2.4 on 2025-07-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignment_state'),
        ('settings', '0007_remove_staff_user_member_alter_subject_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.member'),
        ),
    ]
